// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8GNDz1M9y54cLPIbVkR7Ql_EcUafZis',
    appId: '1:634072339743:android:f79f62e28272370fc8cc2a',
    messagingSenderId: '634072339743',
    projectId: 'chat-ijob-92e27',
    databaseURL: 'https://chat-ijob-92e27-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ijob-92e27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByV8b8lY1_IW8OP15n6tamN_OwVDNYp9w',
    appId: '1:634072339743:ios:29cc7cf7c799a59bc8cc2a',
    messagingSenderId: '634072339743',
    projectId: 'chat-ijob-92e27',
    databaseURL: 'https://chat-ijob-92e27-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ijob-92e27.appspot.com',
    iosClientId: '634072339743-gcicc320pgahv4etq08fb7hkim7sb6do.apps.googleusercontent.com',
    iosBundleId: 'com.app.ijob.ijobApp',
  );
}
